const sampleVideos = [
  {
    id: "dGcsHMXbSOA",
    title: "React Tutorial for Beginners",
    channelTitle: "Code Academy",
    thumbnail: "https://img.youtube.com/vi/dGcsHMXbSOA/mqdefault.jpg",
  },
  {
    id: "W6NZfCO5SIk",
    title: "Learn JavaScript in 1 Hour",
    channelTitle: "Programming Hub",
    thumbnail: "https://img.youtube.com/vi/W6NZfCO5SIk/mqdefault.jpg",
  },
  {
    id: "fYq5PXgSsbE",
    title: "CSS Flexbox Crash Course",
    channelTitle: "Web Dev Simplified",
    thumbnail: "https://img.youtube.com/vi/fYq5PXgSsbE/mqdefault.jpg",
  },
  {
    id: "fBNz5xF-Kx4",
    title: "Node.js Crash Course",
    channelTitle: "Traversy Media",
    thumbnail: "https://img.youtube.com/vi/fBNz5xF-Kx4/mqdefault.jpg",
  },
  {
    id: "_uQrJ0TkZlc",
    title: "Python for Beginners",
    channelTitle: "Programming with Mosh",
    thumbnail: "https://img.youtube.com/vi/_uQrJ0TkZlc/mqdefault.jpg",
  },
  {
    id: "mU6anWqZJcc",
    title: "HTML & CSS Full Course",
    channelTitle: "FreeCodeCamp",
    thumbnail: "https://img.youtube.com/vi/mU6anWqZJcc/mqdefault.jpg",
  },
  {
    id: "RGOj5yH7evk",
    title: "Git & GitHub Crash Course",
    channelTitle: "Academind",
    thumbnail: "https://img.youtube.com/vi/RGOj5yH7evk/mqdefault.jpg",
  },
  {
    id: "f687hBjwFcM",
    title: "React Hooks Explained",
    channelTitle: "Net Ninja",
    thumbnail: "https://img.youtube.com/vi/f687hBjwFcM/mqdefault.jpg",
  },
  {
    id: "NCwa_xi0Uuc",
    title: "JavaScript ES6 Features",
    channelTitle: "Techsith",
    thumbnail: "https://img.youtube.com/vi/NCwa_xi0Uuc/mqdefault.jpg",
  },
  {
    id: "srvUrASNj0s",
    title: "Responsive Web Design",
    channelTitle: "Kevin Powell",
    thumbnail: "https://img.youtube.com/vi/srvUrASNj0s/mqdefault.jpg",
  },
  {
    id: "LAW1J4TqJgA",
    title: "React Router Tutorial",
    channelTitle: "Codevolution",
    thumbnail: "https://img.youtube.com/vi/LAW1J4TqJgA/mqdefault.jpg",
  },
  {
    id: "93p3LxR9xfM",
    title: "Redux Crash Course",
    channelTitle: "Traversy Media",
    thumbnail: "https://img.youtube.com/vi/93p3LxR9xfM/mqdefault.jpg",
  },
  {
    id: "d56mG7DezGs",
    title: "TypeScript Basics",
    channelTitle: "Programming with Mosh",
    thumbnail: "https://img.youtube.com/vi/d56mG7DezGs/mqdefault.jpg",
  },
  {
    id: "0-S5a0eXPoc",
    title: "React Native Tutorial",
    channelTitle: "Academind",
    thumbnail: "https://img.youtube.com/vi/0-S5a0eXPoc/mqdefault.jpg",
  },
  {
    id: "4yqu8YF29cU",
    title: "MongoDB Crash Course",
    channelTitle: "Net Ninja",
    thumbnail: "https://img.youtube.com/vi/4yqu8YF29cU/mqdefault.jpg",
  },
  {
    id: "L72fhGm1tfE",
    title: "Express.js Tutorial",
    channelTitle: "Traversy Media",
    thumbnail: "https://img.youtube.com/vi/L72fhGm1tfE/mqdefault.jpg",
  },
  {
    id: "Q-BpqyOT3a8",
    title: "REST API Tutorial",
    channelTitle: "Code Academy",
    thumbnail: "https://img.youtube.com/vi/Q-BpqyOT3a8/mqdefault.jpg",
  },
  {
    id: "ed8SzALpx1Q",
    title: "GraphQL Crash Course",
    channelTitle: "Academind",
    thumbnail: "https://img.youtube.com/vi/ed8SzALpx1Q/mqdefault.jpg",
  },
  {
    id: "pTFZFxd4hOI",
    title: "Docker for Beginners",
    channelTitle: "TechWorld with Nana",
    thumbnail: "https://img.youtube.com/vi/pTFZFxd4hOI/mqdefault.jpg",
  },
  {
    id: "X48VuDVv0do",
    title: "Kubernetes Explained",
    channelTitle: "TechWorld with Nana",
    thumbnail: "https://img.youtube.com/vi/X48VuDVv0do/mqdefault.jpg",
  },
  {
    id: "35lXWvCuM8o",
    title: "React Context API",
    channelTitle: "Codevolution",
    thumbnail: "https://img.youtube.com/vi/35lXWvCuM8o/mqdefault.jpg",
  },
  {
    id: "mTz0GXj8NN0",
    title: "Next.js Crash Course",
    channelTitle: "Traversy Media",
    thumbnail: "https://img.youtube.com/vi/mTz0GXj8NN0/mqdefault.jpg",
  },
  {
    id: "UBOj6rqRUME",
    title: "Tailwind CSS Tutorial",
    channelTitle: "Net Ninja",
    thumbnail: "https://img.youtube.com/vi/UBOj6rqRUME/mqdefault.jpg",
  },
  {
    id: "9U3IhLAnSxM",
    title: "React Testing Library",
    channelTitle: "Codevolution",
    thumbnail: "https://img.youtube.com/vi/9U3IhLAnSxM/mqdefault.jpg",
  },
  {
    id: "7r4xVDI2vho",
    title: "Jest Crash Course",
    channelTitle: "Academind",
    thumbnail: "https://img.youtube.com/vi/7r4xVDI2vho/mqdefault.jpg",
  },
  {
    id: "0ZJgIjIuY7U",
    title: "React Performance Tips",
    channelTitle: "Codevolution",
    thumbnail: "https://img.youtube.com/vi/0ZJgIjIuY7U/mqdefault.jpg",
  },
  {
    id: "9kRgVxULbag",
    title: "Firebase Crash Course",
    channelTitle: "Traversy Media",
    thumbnail: "https://img.youtube.com/vi/9kRgVxULbag/mqdefault.jpg",
  },
  {
    id: "6g3g0Q6g3mY",
    title: "React Suspense Explained",
    channelTitle: "Academind",
    thumbnail: "https://img.youtube.com/vi/6g3g0Q6g3mY/mqdefault.jpg",
  },
  {
    id: "3Zq2ZzY8Xxw",
    title: "React Server Components",
    channelTitle: "Codevolution",
    thumbnail: "https://img.youtube.com/vi/3Zq2ZzY8Xxw/mqdefault.jpg",
  },
  {
    id: "0fYi8SGA20k",
    title: "React 18 Features",
    channelTitle: "Net Ninja",
    thumbnail: "https://img.youtube.com/vi/0fYi8SGA20k/mqdefault.jpg",
  },
];

export default sampleVideos;
